# Generated by Django 5.2 on 2025-04-03 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Catégorie d'intention",
                'verbose_name_plural': "Catégories d'intentions",
            },
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du bot')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('auto_reply_emails', models.BooleanField(default=True, verbose_name='Répondre aux emails')),
                ('auto_reply_whatsapp', models.BooleanField(default=True, verbose_name='Répondre aux messages WhatsApp')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début des heures de travail')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin des heures de travail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration du bot',
                'verbose_name_plural': 'Configurations du bot',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('keywords', models.TextField(help_text='Séparés par des virgules', verbose_name='Mots-clés')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='api.intentcategory')),
            ],
            options={
                'verbose_name': 'Intention',
                'verbose_name_plural': 'Intentions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Type de message')),
                ('sender', models.CharField(max_length=255, verbose_name='Expéditeur')),
                ('recipient', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processed', 'Traité'), ('replied', 'Répondu'), ('failed', 'Échec')], default='received', max_length=10, verbose_name='Statut')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Niveau de confiance')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intent')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_intents', to='api.message')),
            ],
            options={
                'verbose_name': 'Intention détectée',
                'verbose_name_plural': 'Intentions détectées',
            },
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Les deux')], default='both', max_length=10, verbose_name='Type de modèle')),
                ('is_default', models.BooleanField(default=False, verbose_name='Modèle par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de réponse',
                'verbose_name_plural': 'Modèles de réponse',
            },
        ),
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la réponse')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.message')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsetemplate')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
    ]
